## Python - Introduction:

- Getting started with Python

- Basics

In [1]:
#First code - introduction
print("python_with_Sharjeel")
print(2+3)
print("Hello")
print("starting_python")

python_with_Sharjeel
5
Hello
starting_python


In [11]:
#Operators
print(2+3)
print(56)
print(32/2*3/3+6-4)

#PEMDAS Paranthases exponent multiply divide addition subtration left to rihght seq for m,d and a,s

5
56
18.0


In [9]:
#Strings
print('no one')
print("every one")
print('''some one''')
print("what's up")

no one
every one
some one
what's up


In [42]:
#Comments
print("how are you") #press these to comment out (ctrl + /)
print("we are learning python")  #print a string
print(2+6) #print operators functions with number

how are you
we are learning python
8


In [14]:
#Variables
#Variables: objects containing specific values
x = 5 #numeric variables print(x)
y="we are learning python"
#string variables
print(y)
x= x+10 #or x=15
print(x)

#rules to assign variables

#1. variables should have letter, numbers or underscopes
#2. Donot start with numbers
#3. spaces are not allowed
#4. donot use functional keywords (mean, median, test etc)
#5. short and descriptive
#6. case sensitive (lower should be used)
fruit_basket="mangoes, oranges"
print(fruit_basket)
fruit_basket= 8
print(type(fruit_basket))

#fruit basket
#Input Variables
fruit_basket="mangoes"
print(fruit_basket)

#input function

fruit_basket=input("which is your favourite fruit?")
print(fruit_basket)

name= input("what is your name? ")
greetings="hello!"

print(greetings, name)

we are learning python
15
mangoes, oranges
<class 'int'>
mangoes
mango
hello! Sharjeel


In [12]:
#another way of doing this
name= input("what is your name? ")
print("hello!", name)

hello! Sharjeel


In [13]:
#3rd stage input function
name= input("what is your name")
age= input("how old are you?")
greetings=("hello")

print(greetings, name, "you are still young")

ID= input("what is your ID ?")
Password= input("what is you password ?")
greetings=("Hello!")

print(greetings, "You are welcome")

hello Sharjeel you are still young
Hello! You are welcome


In [18]:
#Conditional logics
#equal to ==
#not equal to !=
#less than <
#greater than >
#less than equal to <=
##greater than equal to >= #logical operators are either "true or false" or "yes or no" or "0 or 1"

#is 4 equal to 4?
print(4==4)
print(4!=4)
print(4>3)
print(3<6)
print(3<=5)
print(5>=4)

True
False
True
True
True
True


In [16]:
#Conversion type
x= 10.2 #integar
y= 10 #float
z= "hello" #string

#implict type

x= x+y

print(x, "type of x is:", type(x))

20.2 type of x is: <class 'float'>


In [15]:
#applications of logical operators
#hammad_age=4
#age_at_shchool=5
#print(hammad_age==age_at_shchool)

#input functions and logical operators
age_at_shchool=5
hammad_age=input("how old is hammad")
#input functions
hammad_age= int(hammad_age)
print(type(hammad_age))
print(hammad_age==age_at_shchool) #logical operators

<class 'int'>
False


In [17]:
#when an integar interact with float, it changes into float

#explict type
age=input("what is age")
age=int(age)
print(type(age))

#2nd way

print(age, type(int(age)))
print(age, type(float(age)))

name=input("what is name")
print(name, type(str(name)))


<class 'int'>
25 <class 'int'>
25 <class 'float'>
Sharjeel <class 'str'>


In [24]:
#If_else_elif
req_age_at_school = 5
ali_age = 1

#can ali go to school
if ali_age==req_age_at_school:
    print("ali can join the school")
elif ali_age > req_age_at_school:
        print("ali should join school")
elif ali_age <= 2:
        print("take care of him")
else:
    print("ali cannot go to school")


take care of him


In [20]:
#if, elif else statement clear
#Functions
#define a functions
def print_lapy():
    print("we are good")
    print("we are good")
    print("we are good")
    print_lapy()

In [21]:
2
def print_lapy():
    text = "we are good"
    print(text)
    print(text)
    print(text)

print_lapy()

we are good
we are good
we are good


In [22]:
#3

def print_lapy(text):
    print(text)
    print(text)
    print(text)

print_lapy("you are good")

you are good
you are good
you are good


In [23]:
#define a function with if, elif and else
def school_calculator(age, text):
    if age==5:
        print("ali can go to school")
    elif age>5:
        print ("ali should go to school")
    else:
            print("ali is too young to school")

school_calculator(2,"ali")

ali is too young to school


In [30]:
#Loops
#while and for loops
#while loops

#x=0 while (x<=5)
#print(x) x=x+1

#for loops

for x in range(4,10):
    print(x)

#array
days= ["mon", "tue", "wed", "thur", "fri","sat"]


import math
print("the value of pi is", math.pi)

import statistics

x= [10, 20, 30, 40]
print(statistics.mean(x))

#numpy, pandas

#Troubleshooting
print("we are learning") #syntax error

#print(25/0) # runtime error

name= "ali"

print("hello name") # symantic error

print("hello", name) #correction of symantic

4
5
6
7
8
9
the value of pi is 3.141592653589793
25
we are learning
hello name
hello ali


In [31]:
# make a string
a = "nice"
a


'nice'

In [32]:
a

'nice'

In [33]:
# length of indices
len(a)

4

In [34]:
a[1]

'i'

In [35]:
a[0:3]

'nic'

In [36]:
a[-4:-1]

'nic'

In [37]:
food = "biryani"
food

'biryani'

String Methods

In [38]:
food

'biryani'

In [39]:
len(food)

7

In [40]:
food.capitalize()

'Biryani'

In [41]:
food.replace("b","sh")

'shiryani'

In [42]:
name  = "Sharjeel with python"
name

'Sharjeel with python'

In [43]:
name.count("h")

3

How to split a string

In [25]:
food = "I love data, analysis and python"
food

'I love data, analysis and python'

In [26]:
food.split(",")

['I love data', ' analysis and python']

Basic Data Structure in Python:

1. Tuple

2. List

3. Dictionaries

4. Set¶

## 1. Tuple:

- orederd collection of elements

- enclosed in ()

- different kind of elements can be stored

- once elements are stored, you canot change it

In [46]:
tup1 = (1, "python", True, 2.5)
tup1

(1, 'python', True, 2.5)

In [47]:
# types of tuple
type(tup1)

tuple

- Indexing in tuple

In [48]:
tup1[1]

'python'

In [49]:
# last element is exclusive
tup1[0:3]

(1, 'python', True)

In [50]:
len(tup1)

4

In [51]:
tup2 = (2, "Hi", False, 3.5)
tup2

(2, 'Hi', False, 3.5)

In [52]:
# concatinate(to add tuples)
tup1 + tup2

(1, 'python', True, 2.5, 2, 'Hi', False, 3.5)

In [53]:
# concatinate + repeat
tup1*2 + tup2

(1, 'python', True, 2.5, 1, 'python', True, 2.5, 2, 'Hi', False, 3.5)

In [56]:
tup3 = (20, 50, 60, 80)
tup3

(20, 50, 60, 80)

In [57]:
tup3*2

(20, 50, 60, 80, 20, 50, 60, 80)

## 2. List:

- orderd collection of elements

- enclosed in square brackets

- you can change the value

In [58]:
list1 =[2, "Hi", False]
list1

[2, 'Hi', False]

In [59]:
type(list1)

list

In [60]:
list2 =[3, 5,"Ali", "Codanics", 478, 53.2, False]
list2

[3, 5, 'Ali', 'Codanics', 478, 53.2, False]

In [61]:
list1 + list2

[2, 'Hi', False, 3, 5, 'Ali', 'Codanics', 478, 53.2, False]

In [62]:
list1.reverse()
list1

[False, 'Hi', 2]

In [63]:
list1.append("how are you")
list1

[False, 'Hi', 2, 'how are you']

In [64]:
list3= [10, 20, 30, 40, 50, 60, 70, 80]
list3

[10, 20, 30, 40, 50, 60, 70, 80]

In [65]:
# sorting
list3.sort()
list3

[10, 20, 30, 40, 50, 60, 70, 80]

In [66]:
list3*3

[10,
 20,
 30,
 40,
 50,
 60,
 70,
 80,
 10,
 20,
 30,
 40,
 50,
 60,
 70,
 80,
 10,
 20,
 30,
 40,
 50,
 60,
 70,
 80]

## 3. Dictionaries:

- unordered collection of element

- key and value

- curly braces or brackets{}

- can change the value

In [27]:
#Food and their prices
food1 = {"apple": 30, "bread": 100, "soda": 10, "salad":50, "chicken roll":100}
food1

{'apple': 30, 'bread': 100, 'soda': 10, 'salad': 50, 'chicken roll': 100}

In [28]:
# extract data
keys1 = food1.keys()
keys1

dict_keys(['apple', 'bread', 'soda', 'salad', 'chicken roll'])

In [29]:
values1 = food1.values()
values1

dict_values([30, 100, 10, 50, 100])

In [30]:
# update the values
food1["milk"]= 15
food1

{'apple': 30,
 'bread': 100,
 'soda': 10,
 'salad': 50,
 'chicken roll': 100,
 'milk': 15}

In [31]:
food2 = {"dates":50, "chocolate":50, "sweets":1000}
food2

{'dates': 50, 'chocolate': 50, 'sweets': 1000}

In [32]:
#concatinate
food1.update(food2)
food1

{'apple': 30,
 'bread': 100,
 'soda': 10,
 'salad': 50,
 'chicken roll': 100,
 'milk': 15,
 'dates': 50,
 'chocolate': 50,
 'sweets': 1000}

## 4. Sets:

- unordered and unindexed

- curly braces {}

- no duplicate

In [2]:
s1 ={1, 2.1, 5.2, "Sharjeel", "Codanica", "Faisalabad", True}
s1

{1, 2.1, 5.2, 'Codanica', 'Faisalabad', 'Sharjeel'}

In [3]:
s1.add("nice")
s1

{1, 2.1, 5.2, 'Codanica', 'Faisalabad', 'Sharjeel', 'nice'}

In [4]:
s1.remove("Codanica")
s1

{1, 2.1, 5.2, 'Faisalabad', 'Sharjeel', 'nice'}

# Numpy

In [ ]:
# pip install numpy

In [1]:
# import this library
import numpy as np

In [3]:
# 1-D array
food =np.array(["tea", "candy","water"])
food

array(['tea', 'candy', 'water'], dtype='<U5')

In [4]:
price =np.array([5, 5, 5])
price

array([5, 5, 5])

In [5]:
type(price)

numpy.ndarray

In [6]:
type(food)

numpy.ndarray

In [7]:
len(food)

3

In [8]:
price[2]

5

In [9]:
price[0:]

array([5, 5, 5])

In [10]:
# zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [11]:
#ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
#empty
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [13]:
#arange
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
#specify arange
np.arange(2, 20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [15]:
#specific arange with specific interval
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
#table
np.arange(5, 55, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [17]:
#specific line space
np.linspace(1, 100, num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [18]:
np.linspace(1, 10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [19]:
#specify data type
np.ones(5, dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [20]:
np.ones(5, dtype=np.float64)

array([1., 1., 1., 1., 1.])

### Array function

In [21]:
a =np.array([10, 12, 15, 2, 4, 6, 100, 320, 0.5, 10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [22]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [23]:
b =np.array([10, 2, 3.5, 53.6, 91.6, 45.5])
b

array([10. ,  2. ,  3.5, 53.6, 91.6, 45.5])

In [24]:
c =np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10. ,   2. ,   3.5,  53.6,  91.6,  45.5])

In [25]:
c.sort()
c

array([  0.5,   2. ,   2. ,   3.5,   4. ,   6. ,  10. ,  10. ,  10.3,
        12. ,  15. ,  45.5,  53.6,  91.6, 100. , 320. ])

### 2-D array

In [26]:
a =np.array([[1, 2, 3, 4], [4, 3, 2, 1]])
a

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [27]:
b =np.array([[6, 7, 8, 9], [9, 8, 7, 6]])
b

array([[6, 7, 8, 9],
       [9, 8, 7, 6]])

In [28]:
c =np.concatenate((a, b), axis=0)
c

array([[1, 2, 3, 4],
       [4, 3, 2, 1],
       [6, 7, 8, 9],
       [9, 8, 7, 6]])

In [29]:
# num of dimension
c.ndim

2

In [30]:
d =np.array([[5, 6, 7],
            [8, 9, 10],
            [11, 12, 13]])
d

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [31]:
d.ndim

2

In [32]:
# number of elements
d.size

9

In [33]:
# shape of element
c.shape

(4, 4)

In [34]:
a =np.arange(9) #3*3
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
#reshape
b =a.reshape(3,3)  # 3*3=9
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
#reshape
np.reshape(a, newshape=(1,9), order ="C")

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [37]:
# convert 1D into 2D
a =np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# row wise conversion
b =a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [39]:
b.shape

(1, 9)

In [40]:
# coloumn wise conversion
c =a[:, np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

# Pandas

In [ ]:
#pip install pandas

In [43]:
# import libraries
import pandas as pd

In [44]:
# Object creation
s =pd.Series([1,3.5,7,8,9])
s

0    1.0
1    3.5
2    7.0
3    8.0
4    9.0
dtype: float64

In [45]:
s =pd.Series([1,3,np.nan ,5,7,8,9])
s

0    1.0
1    3.0
2    NaN
3    5.0
4    7.0
5    8.0
6    9.0
dtype: float64

In [46]:
dates = pd.date_range("20220101", periods =6)
dates

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06'],
              dtype='datetime64[ns]', freq='D')

In [47]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list("ABCD"))
df

A         B         C         D
2022-01-01 -0.524479 -0.590006  0.182707 -1.239319
2022-01-02  0.350771 -2.595268 -1.671142 -1.359675
2022-01-03  0.381263  0.833392 -0.411365 -0.960717
2022-01-04 -0.842862  1.386791  0.206450  0.029339
2022-01-05  0.717486 -0.319246 -0.636587  0.144066
2022-01-06 -1.072817 -0.430672  0.647343  2.160436

In [48]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20220102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["boy", "man","boy","man"]),
        "F": "males",
    }
)
df2

A          B    C  D    E      F
0  1.0 2022-01-02  1.0  3  boy  males
1  1.0 2022-01-02  1.0  3  man  males
2  1.0 2022-01-02  1.0  3  boy  males
3  1.0 2022-01-02  1.0  3  man  males

In [49]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [50]:
df.head(2)

A         B         C         D
2022-01-01 -0.524479 -0.590006  0.182707 -1.239319
2022-01-02  0.350771 -2.595268 -1.671142 -1.359675

In [51]:
df.tail(2)

A         B         C         D
2022-01-05  0.717486 -0.319246 -0.636587  0.144066
2022-01-06 -1.072817 -0.430672  0.647343  2.160436

In [52]:
df.index

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06'],
              dtype='datetime64[ns]', freq='D')

In [53]:
df2.index

Int64Index([0, 1, 2, 3], dtype='int64')

In [54]:
df.to_numpy()

array([[-0.52447852, -0.59000581,  0.18270684, -1.23931917],
       [ 0.35077071, -2.59526766, -1.6711424 , -1.35967511],
       [ 0.38126327,  0.83339227, -0.41136529, -0.96071664],
       [-0.84286235,  1.38679112,  0.20645029,  0.02933939],
       [ 0.71748631, -0.31924597, -0.63658667,  0.14406622],
       [-1.07281689, -0.43067223,  0.64734346,  2.16043557]])

In [55]:
df2.to_numpy()

array([[1.0, Timestamp('2022-01-02 00:00:00'), 1.0, 3, 'boy', 'males'],
       [1.0, Timestamp('2022-01-02 00:00:00'), 1.0, 3, 'man', 'males'],
       [1.0, Timestamp('2022-01-02 00:00:00'), 1.0, 3, 'boy', 'males'],
       [1.0, Timestamp('2022-01-02 00:00:00'), 1.0, 3, 'man', 'males']],
      dtype=object)

In [56]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.165106 -0.285835 -0.280432 -0.204312
std    0.742436  1.378292  0.823454  1.322592
min   -1.072817 -2.595268 -1.671142 -1.359675
25%   -0.763266 -0.550172 -0.580281 -1.169669
50%   -0.086854 -0.374959 -0.114329 -0.465689
75%    0.373640  0.545233  0.200514  0.115385
max    0.717486  1.386791  0.647343  2.160436

In [57]:
# to transport data
df2.T

0                    1                    2  \
A                  1.0                  1.0                  1.0   
B  2022-01-02 00:00:00  2022-01-02 00:00:00  2022-01-02 00:00:00   
C                  1.0                  1.0                  1.0   
D                    3                    3                    3   
E                  boy                  man                  boy   
F                males                males                males   

                     3  
A                  1.0  
B  2022-01-02 00:00:00  
C                  1.0  
D                    3  
E                  man  
F                males

In [58]:
df.sort_index(axis=1, ascending=True)

A         B         C         D
2022-01-01 -0.524479 -0.590006  0.182707 -1.239319
2022-01-02  0.350771 -2.595268 -1.671142 -1.359675
2022-01-03  0.381263  0.833392 -0.411365 -0.960717
2022-01-04 -0.842862  1.386791  0.206450  0.029339
2022-01-05  0.717486 -0.319246 -0.636587  0.144066
2022-01-06 -1.072817 -0.430672  0.647343  2.160436

In [59]:
df.sort_index(axis=0, ascending=True)

A         B         C         D
2022-01-01 -0.524479 -0.590006  0.182707 -1.239319
2022-01-02  0.350771 -2.595268 -1.671142 -1.359675
2022-01-03  0.381263  0.833392 -0.411365 -0.960717
2022-01-04 -0.842862  1.386791  0.206450  0.029339
2022-01-05  0.717486 -0.319246 -0.636587  0.144066
2022-01-06 -1.072817 -0.430672  0.647343  2.160436

In [60]:
df.sort_index(axis=0, ascending=False)

A         B         C         D
2022-01-06 -1.072817 -0.430672  0.647343  2.160436
2022-01-05  0.717486 -0.319246 -0.636587  0.144066
2022-01-04 -0.842862  1.386791  0.206450  0.029339
2022-01-03  0.381263  0.833392 -0.411365 -0.960717
2022-01-02  0.350771 -2.595268 -1.671142 -1.359675
2022-01-01 -0.524479 -0.590006  0.182707 -1.239319

In [61]:
df.sort_values(by="B")

A         B         C         D
2022-01-02  0.350771 -2.595268 -1.671142 -1.359675
2022-01-01 -0.524479 -0.590006  0.182707 -1.239319
2022-01-06 -1.072817 -0.430672  0.647343  2.160436
2022-01-05  0.717486 -0.319246 -0.636587  0.144066
2022-01-03  0.381263  0.833392 -0.411365 -0.960717
2022-01-04 -0.842862  1.386791  0.206450  0.029339

In [62]:
# sorting - filtering - selection
df["A"]

2022-01-01   -0.524479
2022-01-02    0.350771
2022-01-03    0.381263
2022-01-04   -0.842862
2022-01-05    0.717486
2022-01-06   -1.072817
Freq: D, Name: A, dtype: float64

In [63]:
# row wise selection
df[0:2]

A         B         C         D
2022-01-01 -0.524479 -0.590006  0.182707 -1.239319
2022-01-02  0.350771 -2.595268 -1.671142 -1.359675

In [64]:
df[0:1]

A         B         C         D
2022-01-01 -0.524479 -0.590006  0.182707 -1.239319

In [65]:
df[1:5]

A         B         C         D
2022-01-02  0.350771 -2.595268 -1.671142 -1.359675
2022-01-03  0.381263  0.833392 -0.411365 -0.960717
2022-01-04 -0.842862  1.386791  0.206450  0.029339
2022-01-05  0.717486 -0.319246 -0.636587  0.144066

In [66]:
# row wise
df.loc[dates[0]]

A   -0.524479
B   -0.590006
C    0.182707
D   -1.239319
Name: 2022-01-01 00:00:00, dtype: float64

In [67]:
# coloumn wise
df.loc[:, ["A", "B"]]

A         B
2022-01-01 -0.524479 -0.590006
2022-01-02  0.350771 -2.595268
2022-01-03  0.381263  0.833392
2022-01-04 -0.842862  1.386791
2022-01-05  0.717486 -0.319246
2022-01-06 -1.072817 -0.430672

In [68]:
df.loc["2022-01-02":"2022-01-04", ["A", "B"]]

A         B
2022-01-02  0.350771 -2.595268
2022-01-03  0.381263  0.833392
2022-01-04 -0.842862  1.386791

In [69]:
df.loc["2022-01-02", ["A", "B", "C"]]

A    0.350771
B   -2.595268
C   -1.671142
Name: 2022-01-02 00:00:00, dtype: float64

In [70]:
df.at[dates[4], "A"]

0.7174863124346677

In [71]:
# what is at specific position positionwise
df.iloc[3]

A   -0.842862
B    1.386791
C    0.206450
D    0.029339
Name: 2022-01-04 00:00:00, dtype: float64

In [72]:
df.iloc[3:10]

A         B         C         D
2022-01-04 -0.842862  1.386791  0.206450  0.029339
2022-01-05  0.717486 -0.319246 -0.636587  0.144066
2022-01-06 -1.072817 -0.430672  0.647343  2.160436

In [73]:
df.iloc[0:2, 0:3]

A         B         C
2022-01-01 -0.524479 -0.590006  0.182707
2022-01-02  0.350771 -2.595268 -1.671142

In [74]:
df.iloc[0:4, :]

A         B         C         D
2022-01-01 -0.524479 -0.590006  0.182707 -1.239319
2022-01-02  0.350771 -2.595268 -1.671142 -1.359675
2022-01-03  0.381263  0.833392 -0.411365 -0.960717
2022-01-04 -0.842862  1.386791  0.206450  0.029339

In [75]:
df.iloc[:, 0:2]

A         B
2022-01-01 -0.524479 -0.590006
2022-01-02  0.350771 -2.595268
2022-01-03  0.381263  0.833392
2022-01-04 -0.842862  1.386791
2022-01-05  0.717486 -0.319246
2022-01-06 -1.072817 -0.430672

In [76]:
# to find value more or less than specific value
df[df["A"] > 0]

A         B         C         D
2022-01-02  0.350771 -2.595268 -1.671142 -1.359675
2022-01-03  0.381263  0.833392 -0.411365 -0.960717
2022-01-05  0.717486 -0.319246 -0.636587  0.144066

In [77]:
df[df< 0]

A         B         C         D
2022-01-01 -0.524479 -0.590006       NaN -1.239319
2022-01-02       NaN -2.595268 -1.671142 -1.359675
2022-01-03       NaN       NaN -0.411365 -0.960717
2022-01-04 -0.842862       NaN       NaN       NaN
2022-01-05       NaN -0.319246 -0.636587       NaN
2022-01-06 -1.072817 -0.430672       NaN       NaN

In [78]:
df2 =df.copy()
df2["E"]=["one", "two","three","four","three", "one"]
df2

A         B         C         D      E
2022-01-01 -0.524479 -0.590006  0.182707 -1.239319    one
2022-01-02  0.350771 -2.595268 -1.671142 -1.359675    two
2022-01-03  0.381263  0.833392 -0.411365 -0.960717  three
2022-01-04 -0.842862  1.386791  0.206450  0.029339   four
2022-01-05  0.717486 -0.319246 -0.636587  0.144066  three
2022-01-06 -1.072817 -0.430672  0.647343  2.160436    one

In [80]:
df2["new"]=[1.2,2.2,3.2,4.2,5.2,6.2]
df2
df2= df2.iloc[:, 0:3]
df2

A         B         C
2022-01-01 -0.524479 -0.590006  0.182707
2022-01-02  0.350771 -2.595268 -1.671142
2022-01-03  0.381263  0.833392 -0.411365
2022-01-04 -0.842862  1.386791  0.206450
2022-01-05  0.717486 -0.319246 -0.636587
2022-01-06 -1.072817 -0.430672  0.647343